#!/bin/bash
#
# Author: Kun Sun @ SZBL (sunkun@szbl.ac.cn)
# Date  : 2023.6.6
#
set -o nounset
set -o errexit

VERSION="1.2.0, Jun 2023"

## changes in v1.2:
## Add option "-e" to set completeMappingRatio
## Add option "-Q" to set min mapQ
## Pipe FLASH outputs with cut
## Change the default aligner to BWA

function usage() {
echo -e "
\033[1;34mUsage: microcket [options] -i <fq.list> -o <sid>\033[0m

Authors : Yu Zhao, Mengqi Yang, Qin Peng, Leina Lu, Xiaowen Lyu, Kun Sun
Software: Kun Sun (sunkun@szbl.ac.cn)
Version : $VERSION

Microcket is a flexible toolkit for Hi-C/Micro-C/HiChIP/MicroChIP data analysis.
It has been specifically optimized for long-cycle (100 or longer) reads.

Options:
  -i fq.list   Specify an input file recording paths to fastq files
                   Multiple lanes of data are supported; gzip-ed files are also supported.
  -o sid       Set sample id, which will be used as prefix of all output files

  -g genome    Set genome. Default hg38.
  -b           Set this flag to keep inter-lane duplications (e.g., biological replicates)
  -k kit       Set sequencing kit for adaptor-trimming. Default: illumina
                   Supports bgi, illumina, nextera.
  -m mode      Set read stitch mode. Default: auto
                   Supports yes, no, auto

  -a aligner   Set underline aligner. Default: BWA
                   Supports STAR, BWA, STAR-BWA, BWA-STAR
  -S           Set to enable splicing-aware mode of STAR
  -e VALUE     Set the minimum alignable proportion of a read to consider as complete mapping
                   Default: 0.5. Must be a number between 0 and 1.
  -Q VALUE     Set the minimum mapping quality for a read to be considered. Default: 10

  -r r1[,r2]   Set resolutions in hic file (use ',' to separate multiple values)
                   Default: 2500000,1000000,500000,250000,100000,50000,25000,10000,5000
                   Note: if your parameter starts with ',', I will add it to the default values
  -u           Set to generate UCSC-compatible hic files (\e[4mslower\e[0m)
  -c           Set to generate cool files (require \e[3mcooler\e[m package; \e[4mtakes time\e[0m)
                   Note: the smallest bin in '-r' will be used during cool file generation.
  -x           Set to skip BAM file generation.

  -t thread    Set running threads
                   Default: all threads available (\e[1;34mrequire >=4\e[0m)

  -q           Set this flag to run in quiet mode (only report fatal errors)
  -v           Show software version and quit
  -h           Show this help information and quit

\033[1;34mMicrocket is freely available at https://github.com/hellosunking/Microcket\033[0m
"
}

if [ $# -lt 1 ]
then
	usage
	exit 2
fi >/dev/stderr

## Microcket root directory
MDR=`readlink -f $0`
MDR=`dirname $MDR`
PRG="$MDR/bin"
ANNO="$MDR/anno"

## default parameters
infile=""
sid=""

genome="hg38"
aligner="BWA"
seqKit="illumina"
catmod="auto"
thread=0
resolution="2500000,1000000,500000,250000,100000,50000,25000,10000,5000"
completeMappingRatio=0.5
minMapQ=10
biorep="no"
enableSplicing="no"
ucscHic="no"
cooler="no"
quietmode="no"
showVer="no"
showHelp="no"
writeBam="yes"

## parse parameters
while getopts ":i:o:g:a:k:m:r:e:Q:t:Sbucxqvh" OPTION
do
	case $OPTION in
		i)infile="$OPTARG"
			;;
		o)sid="$OPTARG"
			;;
		g)genome="$OPTARG"
			;;
		a)aligner="$OPTARG"
			;;
		k)seqKit="$OPTARG"
			;;
		m)catmod="$OPTARG"
			;;
		r)resolution="$OPTARG"
			;;
		e)completeMappingRatio="$OPTARG"
			;;
		Q)minMapQ="$OPTARG"
			;;
		t)thread="$OPTARG"
			;;
		S)enableSplicing="yes"
			;;
		b)biorep="yes"
			;;
		u)ucscHic="yes"
			;;
		c)cooler="yes"
			;;
		x)writeBam="no"
			;;
		q)quietmode="yes"
			;;
		v)showVer="yes"
			;;
		h)showHelp="yes"
			;;
		?)echo "ERROR: unsupported option detected." && exit 2
			;;
	esac
done >/dev/stderr

if [ $showVer == "yes" ]
then
	echo $VERSION
	exit 0
fi

if [ $showHelp == "yes" ]
then
	usage
	exit 0
fi

## check parameters
if [ -z "$infile" ] || [ -z "$sid" ]
then
	echo "ERROR: compulsory parameters (-i/-o) are missing!" >/dev/stderr
	exit 1
fi
if [ ! -s "$infile" ]
then
	echo "ERROR: input file does not exist!" >/dev/stderr
	exit 3
fi

if [ ${resolution:0:1} == "," ]
then
	resolution="2500000,1000000,500000,250000,100000,50000,25000,10000,5000$resolution"
	[ $quietmode == "yes" ] || echo "INFO: resolution is set to $resolution."
fi

## check aligner and index
sindex="$MDR/index/STAR/$genome"
bindex="$MDR/index/BWA/$genome"
if [ $aligner == "STAR" ] || [ $aligner == "star" ]
then
	if [ ! -s "$sindex/SA" ]
	then
		echo "ERROR: STAR index for $genome is missing!" >/dev/stderr
		exit 10
	fi
	aligner_flash="STAR"
	aligner_unc="STAR"
elif [ $aligner == "BWA" ] || [ $aligner == "bwa" ]
then
	if [ ! -s "$bindex.sa" ]
	then
		echo "ERROR: BWA index for $genome is missing!" >/dev/stderr
		exit 10
	fi
	aligner_flash="BWA"
	aligner_unc="BWA"
elif [ $aligner == "STAR-BWA" ] || [ $aligner == "star-bwa" ]
then
	if [ ! -s "$sindex/SA" ]
	then
		echo "ERROR: STAR index for $genome is missing!" >/dev/stderr
		exit 10
	fi
	if [ ! -s "$bindex.sa" ]
	then
		echo "ERROR: BWA index for $genome is missing!" >/dev/stderr
		exit 10
	fi
	aligner_flash="STAR"
	aligner_unc="BWA"
elif [ $aligner == "BWA-STAR" ] || [ $aligner == "bwa-star" ]
then
	if [ ! -s "$sindex/SA" ]
	then
		echo "ERROR: STAR index for $genome is missing!" >/dev/stderr
		exit 10
	fi
	if [ ! -s "$bindex.sa" ]
	then
		echo "ERROR: BWA index for $genome is missing!" >/dev/stderr
		exit 10
	fi
	aligner_flash="BWA"
	aligner_unc="STAR"
else
	echo "ERROR: Unsupported aligner! Currently Microcket only supports STAR, BWA, STAR-BWA, or BWA-STAR." >/dev/stderr
	exit 10
fi

GINFO="$ANNO/$genome.info"
samheader="$ANNO/$genome.sam.header"
if [ ! -s "$GINFO" ] || [ ! -s "$samheader" ]
then
	echo "ERROR: annotation file for $genome is missing!" >/dev/stderr
	exit 10
fi

## others
## seqKit will be checked by ktrim, so I do not need to check it here
if [ $catmod != "yes" ] && [ $catmod != "no" ] && [ $catmod != "auto" ]
then
	echo "ERROR: unknown catmode! Must be yes, no, or auto." >/dev/stderr
	exit 11
fi

if [ $thread == "0" ]	## use all threads
then
	thread=`cat /proc/cpuinfo | grep processor | wc -l`
	echo "INFO: $thread threads will be used."
fi

if [ $thread -lt 4 ]
then
	echo "ERROR: at least 4 threads are needed." >/dev/stderr
	exit 12
fi

## I have included pre-complied Ktrim, flash, samtools, STAR, bwa in this package
## check cooler, which is a python package and could NOT be included
if [ $cooler == "yes" ]
then
	COOLER=`which cooler || echo ""`
	if [ -z $COOLER ]
	then
		echo "ERROR: Cooler is NOT found but you have set '-c'!" >/dev/stderr
		exit 100
	else
		[ $quietmode == "yes" ] || echo "INFO: Cooler is found at '$COOLER'."
	fi
fi

########################## START ANALYSIS ############################################
## extract input files
R1s=""
R2s=""
fileCnt=0
declare -a R1s_arr
declare -a R2s_arr
while read fq1 fq2 extra
do
	[ ${fq1:0:1} == "#" ] && continue

	## TODO: change to absolute path?
	if [ -z "$fq2" ]
	then
		echo "ERROR: invalid input file! Each lane must contain both read1 and read2!" >/dev/stderr
		exit 21
	fi

	R1s="$R1s,$fq1"
	R2s="$R2s,$fq2"
	R1s_arr[$fileCnt]=$fq1
	R2s_arr[$fileCnt]=$fq2

	let fileCnt=$fileCnt+1
done < $infile

## remove the head ','
R1fq=${R1s:1}
R2fq=${R2s:1}

if [ $fileCnt -eq 1 ] && [ $biorep == "yes" ]	## only 1 file, but -b is set
then
	[ $quietmode == "yes" ] || echo "WARNING: Only 1 lane is provided; '-b' option is meaningless and will be ignored."
	biorep="no"
fi

## parameters for STAR
minIntron=20
maxIntron=10000
minChim=20
if [ $enableSplicing == "yes" ]
then
	STARparam="--genomeDir $sindex --runThreadN $thread --outSAMtype BAM Unsorted --chimOutType WithinBAM --outBAMcompression 0 --outSAMunmapped None --outSAMattributes Standard --alignIntronMin $minIntron --alignIntronMax $maxIntron --scoreGapNoncan 4 --chimScoreJunctionNonGTAG 0 --chimSegmentMin $minChim"
else
	STARparam="--genomeDir $sindex --runThreadN $thread --outSAMtype BAM Unsorted --chimOutType WithinBAM --outBAMcompression 0 --outSAMunmapped None --outSAMattributes Standard --alignIntronMax 1 --scoreGapNoncan 4 --chimScoreJunctionNonGTAG 0 --chimSegmentMin $minChim"
fi

## start analysis
datetime=`date`
[ $quietmode == "yes" ] || echo "########## Microcket starts on $datetime ##########"

[ $quietmode == "yes" ] || echo "Check stitch strategy ..."
##minConcatCycle=99
minConcatCycle=150
## in auto mode: check read cycle, if too short, i.e., < 100, then do not do flash combine
## for HiC, most protocols generate ~400 bp fragments therefore PE150 could not read through
## TODO: add file.existence check in check.cycle.pl
if [ $catmod == "auto" ]
then
	seqCycle=`perl $PRG/check.cycle.pl $infile`
	if [ $? != 0 ]	## error occurs
	then
		exit $?
	fi

	if [ $seqCycle -lt $minConcatCycle ]
	then
		[ $quietmode == "yes" ] || echo "INFO: input reads are too short, read stitch will be skipped."
		DoSTITCH="no"
	else
		[ $quietmode == "yes" ] || echo "INFO: input reads are long enough for stitching."
		DoSTITCH="yes"
	fi
elif [ $catmod == "no" ]
then
	DoSTITCH="no"
	[ $quietmode == "yes" ] || echo "INFO: read stitch will be skipped."
else
	DoSTITCH="yes"
	[ $quietmode == "yes" ] || echo "INFO: read stitch will be forced."
fi

## read preprocessing
## NOTE: Ktrim v1.5.0 or higher is required
kthread=4
[ $thread -ge 8 ] && kthread=6
if [ $biorep == "no" ]
then
	[ $quietmode == "yes" ] || echo "Read preprocessing ..."
	## the modified combo is 3x faster than the normal ktrim+krmdup
	if [ $DoSTITCH == "yes" ] 
	then
		$PRG/ktrim -c -k $seqKit -t $kthread -o $sid -1 $R1fq -2 $R2fq -c | \
		$PRG/krmdup.pipe -i /dev/stdin -o $sid.rmdup | \
		$PRG/flash -q --interleaved-input -m 10 -M 150 -t $thread -o $sid.flash -To -c - | \
		perl $PRG/deal.flash.pl - $sid
		## cut the tailing 10 cycles in notCombined reads
		## This is because flash will not combine those with < 10 bp overlap
	else
		rm -f $sid.rmdup.read1.fq $sid.rmdup.read2.fq
		$PRG/ktrim -c -k $seqKit -t $kthread -o $sid -1 $R1fq -2 $R2fq -c | $PRG/krmdup -i /dev/stdin -o $sid.rmdup
		ln -sf $sid.rmdup.read1.fq $sid.cut.read1.fq
		ln -sf $sid.rmdup.read2.fq $sid.cut.read2.fq
	fi

	if [ $? != 0 ]
	then
		echo "ERROR: preprcessing failed! Please check your fastq files!" >/dev/stderr
		exit 31
	fi
else	## biological repolicates; including multi-index during library preparation
	[ $quietmode == "yes" ] || echo "Read preprocessing (as biological replicates) ..."

	if [ $DoSTITCH == "yes" ]
	then
		for i in ${!R1s_arr[@]}
		do
			$PRG/ktrim -c -k $seqKit -t $kthread -o $sid.$i -1 ${R1s_arr[$i]} -2 ${R2s_arr[$i]} -c | \
			$PRG/krmdup.pipe -i /dev/stdin -o $sid.rmdup
			if [ $? != 0 ]
			then
				echo "ERROR: preprcessing failed! Check your fastq files!" >/dev/stderr
				exit 31
			fi
		done | $PRG/flash -q --interleaved-input -m 10 -M 150 -t $thread -o $sid.flash -To -c - | \
		perl $PRG/deal.flash.pl - $sid
		cat $sid.*.trim.log >$sid.trim.log
	else
		rm -f $sid.rmdup.read1.fq $sid.rmdup.read2.fq
		for i in ${!R1s_arr[@]}
		do
			$PRG/ktrim -c -k $seqKit -t $kthread -o $sid.$i -1 ${R1s_arr[$i]} -2 ${R2s_arr[$i]} -c | \
			$PRG/krmdup -i /dev/stdin -o $sid.rmdup
			if [ $? != 0 ]
			then
				echo "ERROR: preprcessing failed! Check your fastq files!" >/dev/stderr
				exit 31
			fi
		done
		cat $sid.*.trim.log >$sid.trim.log
		ln -sf $sid.rmdup.read1.fq $sid.cut.read1.fq
		ln -sf $sid.rmdup.read2.fq $sid.cut.read2.fq
	fi
fi

## alignment
## thread for pipes
vthread=4
if [ $thread -ge 8 ]
then
	sthread=8
else
	sthread=4
fi

cp $ANNO/4DN.DCIC.header $sid.final.pairs
if [ $DoSTITCH == "yes" ]
then
	[ $quietmode == "yes" ] || echo "Map stitched reads using $aligner_flash and generate pairs ..."
	## alignment on flash-combined reads
	if [ $aligner_flash == "STAR" ]
	then
		mkdir -p $sid.STAR/
		$PRG/STAR $STARparam \
			--readFilesIn $sid.ext.fq \
			--outFileNamePrefix $sid.STAR/flash. >$sid.STAR/flash.run.log

		$PRG/samtools view -@ $vthread $sid.STAR/flash.Aligned.out.bam | \
		$PRG/sam2pairs /dev/stdin flash $sid $sthread $completeMappingRatio $minMapQ $writeBam | \
		LANG=C sort -k2,2d -k4,4d -k3,3n -k5,5n --parallel=$thread -S 50% >$sid.flash.pairs
	else	## BWA
		$PRG/bwa mem -5 -T 10 -v 2 -t $thread $bindex $sid.ext.fq 2>$sid.bwa.ext.log | \
		$PRG/sam2pairs /dev/stdin flash $sid $sthread $completeMappingRatio $minMapQ $writeBam | \
		LANG=C sort -k2,2d -k4,4d -k3,3n -k5,5n --parallel=$thread -S 50% >$sid.flash.pairs
	fi

	uncfile=$sid.unc.pairs
	rm -f $sid.unc.pairs
else
	uncfile=$sid.final.pairs
fi

## alignment on uncombined reads
[ $quietmode == "yes" ] || echo "Map un-stitched reads using $aligner_unc and generate pairs ..."
if [ $aligner_unc == "STAR" ]
then
	mkdir -p $sid.STAR/
	$PRG/STAR $STARparam \
		--readFilesIn $sid.cut.read1.fq $sid.cut.read2.fq \
		--outFileNamePrefix $sid.STAR/unc. >$sid.STAR/unc.run.log

	$PRG/samtools view -@ $vthread $sid.STAR/unc.Aligned.out.bam | \
	$PRG/sam2pairs /dev/stdin unc $sid $sthread $completeMappingRatio $minMapQ $writeBam | \
	LANG=C sort -k2,2d -k4,4d -k3,3n -k5,5n --parallel=$thread -S 50% >>$uncfile
else
	$PRG/bwa mem -5SP -T 10 -v 2 -t $thread $bindex $sid.cut.read1.fq $sid.cut.read2.fq 2>$sid.bwa.unc.log | \
	$PRG/sam2pairs /dev/stdin unc $sid $sthread $completeMappingRatio $minMapQ $writeBam | \
	LANG=C sort -k2,2d -k4,4d -k3,3n -k5,5n --parallel=$thread -S 50% >>$uncfile
fi

## NOTE: this header is essential for juicerbox to recognize the format
## -k3,3n -k5,5n is essential for pairix and cooler
if [ -s $sid.flash.pairs ]	## Stitch occurs, there should be 2 sorted pairs files, merge them
then
	[ $quietmode == "yes" ] || echo "Pool pairs ..."
	LANG=C sort -k2,2d -k4,4d -k3,3n -k5,5n --parallel=$thread -S 50% -m $sid.flash.pairs $sid.unc.pairs >>$sid.final.pairs
fi

[ $quietmode == "yes" ] || echo "Generate analysis statistics ..."
perl $PRG/make.stat.pl $sid $DoSTITCH >$sid.final.stat

## convert to hic format
[ $quietmode == "yes" ] || echo "Convert to hic format (please be patient) ..."
if [ $ucscHic == "yes" ]
then
	## a relatively old version of juicer tool will be used to be compatible with UCSC
	java -Xmx4g -jar $PRG/juicer_tools.ucsc.jar pre -r $resolution $sid.final.pairs $sid.hic $GINFO &
else
	## newer versions supports "--threads"
	## but does not speed-up significantly with multi-threads
	java -Xmx32g -jar $PRG/juicer_tools.jar pre --threads $sthread -r $resolution $sid.final.pairs $sid.hic $GINFO &
fi >$sid.juicer.log 2>&1

## convert to cooler format and do normalization
if [ $cooler == "yes" ]
then
	[ $quietmode == "yes" ] || echo "Convert to cool format (please be patient) ..."
	## this combo is faster than "cooler cload pairs", because the later does not support multi-thread
	## bgzip is very slow
	$PRG/bgzip -c $sid.final.pairs >$sid.final.pairs.gz
	$PRG/pairix $sid.final.pairs.gz
	minBIN=`echo $resolution | perl -ne '@r=split /,/; @s=sort {$a<=>$b} @r; print $s[0]'`
	cooler cload pairix -p $thread $GINFO:$minBIN $sid.final.pairs.gz $sid.$minBIN.cool >$sid.cooler.log 2>&1
#	cooler zoomify --balance -p $thread $sid.$minBIN.cool >>$sid.cooler.log 2>&1
	## the final output is $sid.1kb.cool
	wait
fi

## generate final mapping results
if [ $writeBam == "yes" ]
then
	[ $quietmode == "yes" ] || echo "Generate filtered alignment results (please be patient) ..."
	touch $sid.flash.sam
	cat $samheader $sid.flash.sam $sid.unc.sam | $PRG/samtools view -@ $vthread --no-PG -b /dev/stdin | \
	$PRG/samtools sort -@ $thread -m 2G --no-PG -o $sid.valid.bam /dev/stdin 2>/dev/null
	$PRG/samtools index -@ $thread $sid.valid.bam
fi
wait

## clean up
[ $quietmode == "yes" ] || echo "Clean up intermediate files ..."
rm -f $sid.*.fq $sid.*.sam $sid.STAR/*bam
rm -f $sid.flash.pairs $sid.unc.pairs

datetime=`date`
[ $quietmode == "yes" ] || echo "########## Microcket finishes on $datetime ##########"

